// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer: dynamic(() => import("./Footer")),
  hubspot_form: dynamic(() => import("./HubspotForm")),
  rich_text: dynamic(() => import("./RichText")),
};
